version: '3.8'

services:
  app: &app_base
    build:
      context: .
      dockerfile: ./app/Dockerfile
      args:
        RUBY_VERSION: '3.0.3'
        NODE_VERSION: '17.2.0' # 10 , 12 , 14 , 15
        PROJECT_NAME: 'kbot'
        DOCCOM_DIR: 'app'
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: bash -c "bundle install && ./bin/dev"
    ports:
      - 3000:3000
    depends_on:
      - mysql
    volumes:
      # - ./app:/kbot:cached
      - ./app:/kbot
    environment:
      RAILS_ENV: development
      DATABASE_HOST: mysql
      DATABASE_USER: root
      DATABASE_PASSWORD: password


  mysql:
    image: public.ecr.aws/docker/library/mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql


volumes:
  mysql-data:
  tmp-data:
  redis-data:



